### ISSUE TITLE
fatal: Not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by bblumenfelder** [chartes/deucalion-model-lasla#9]
Unfortunately I cannot run this docker image. I tried it running it on one windows and a linux machine.
Whenever I run
`docker run -p 5001:5000 ponteineptique/deucalion-model-lasla:latest`

I get the following error:
```
[2020-02-09 14:33:38 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2020-02-09 14:33:38 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2020-02-09 14:33:38 +0000] [1] [INFO] Using worker: sync
[2020-02-09 14:33:38 +0000] [8] [INFO] Booting worker with pid: 8
fatal: Not a git repository (or any of the parent directories): .git
[2020-02-09 14:33:39 +0000] [8] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/app/flaskapp.py", line 4, in <module>
    from flask_pie.disambiguator.autocat import Autocat
ModuleNotFoundError: No module named 'flask_pie.disambiguator'
[2020-02-09 14:33:39 +0000] [8] [INFO] Worker exiting (pid: 8)
[2020-02-09 14:33:39 +0000] [1] [INFO] Shutting down: Master
[2020-02-09 14:33:39 +0000] [1] [INFO] Reason: Worker failed to boot.
```

**Comment by PonteIneptique** [comment]
You're right, the dev here might be a little stale. We have worked on fixing the inners of the lemmatizer, which you can find here : https://github.com/hipster-philology/nlp-pie-taggers . 

If this is really about the build, I'll have a look this week but I can't promis anything :)

**Comment by bblumenfelder** [comment]
Thanks! I'd love to get it running 🙇‍♂️

**Comment by PonteIneptique** [comment]
A new build is coming. There was a stupid mistake on the parent docker image. :)

**Comment by PonteIneptique** [comment]
Build is done, feel free to tell me if you have issue running it ;)

**Comment by bblumenfelder** [comment]
Perfect, its running - many thanks!
